#!/bin/bash

wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
pkexec gdebi-gtk --auto-close google-chrome-stable_current_amd64.deb
rm google-chrome-stable_current_amd64.deb