#!/bin/bash

wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo gdebi -q -n google-chrome-stable_current_amd64.deb
rm google-chrome-stable_current_amd64.deb
touch chrome-k
